City-of-Helsinki/kerrokantasi-ui

- package.json
This is really only an issue on npm 3+
> Add missing peer dependency for Leaflet

- package.json
Idea here is to have a single preparation command "npm run build". This command is supposed to performs all steps beyond "npm i", that are necessary to prepare the codebase for running within a process manager.
npm also supports lifecycle events for automating this, but I cannot tell if using them would cause difficulties elsewhere.
> Add build script for npm

- src/components/OverviewMap.js
Properly set max bounds makes sure that the hearing map can't be
accidentally scrolled or zoomed out of the Helsinki area.
This should improve the user experience of the map component.
Refs: #204
> Set max bounds to hearing map

- package.json
react-leaflet-draw (which will be need in admin UI) doesn't work with
react-leaflet@0.12.
Information about the breaking change:
https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v0120-2016-06-25
> Downgrade react-leaflet version

- src/i18n/fi.json
- src/views/admin/AdminHearings.js
The view contains published hearings, hearing publishing queue and
draft hearings. It isn't added to any route yet.
> Add initial Hearings view with tabs for admins

- src/actions/index.js
- src/components/Comment.js
- test/comment.js
**Supersedes:** #212
**Fixes:** #203
<hr>
Removed previously used vote button from comment and changed the thumb to act as a
vote button.
Thumb is always clickable, but when user can not vote, an error
message is shown.
Refs: #203
**Screenshot of the voting thumb**
**Login to vote**
> Thumb vote (resubmission)

- src/components/Hearing.js
- src/views/Hearing/index.js
Split views/Hearing/index.js into separate view and component. This
way reusing the Hearing becomes easier and we can reuse the Hearing
component in other views for example.
This work makes admin UI implementation easier.
> Refactor Hearing into separate component and view

- package.json
- src/components/BaseCommentForm.js
- src/components/plugins/mapdon-hkr.js
- src/components/plugins/mapdon-ksv.js
Upgrade react-bootstrap from 0.29.5 to 0.30.5
- [Changelog](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#v0300)
- Required replacing `Input` components with `FormControl`s
Upgrade react-leaflet from 0.11.5 to 0.11.7
- [Changelog](https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v0117-2016-06-14)
- Bug fixes. Seemed to work, though automated test coverage is mostly non-existing.
> Upgrade bs and leaflet

- package.json
- src/components/OverviewMap.js
This gives us some bug fixes, but most notably support for newer
versions of react-leaflet-draw which is required by becoming admin UI.
[Changelog](https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md)
From the changelog.
> [BREAKING] Moved Leaflet instances injection from props to context. All components provided by this lib should continue to work as expected, but custom components need to be updated. Read the UPGRADING file for more information.
That change breaks newer versions of `react-leaflet-draw` and that's the main reason for this upgrade.
> Upgrade react-leaflet from 0.11.7 to ^0.12.3

- src/components/Comment.js
The button probably slipped back into the master during some merge
conflict solving (it happens :)). During PR #225 merging.
Now deprecated voteButton is correctly removed.
> Remove voteButton from comment body

- assets/less/hel/fullscreen-map-plugin.less
Few elements lacked height 100% to support fullscreen map plugin
properly on IE browsers.
> Fix fullscreen map height problem on IE's

- __tests__/LabelList.react-test.js
- __tests__/__snapshots__/LabelList.react-test.js.snap
- src/components/LabelList.js
Hearing.labels are used to be sent as list of strings, but because UI
needs labels ids the API is going to change. Therefore LabelList now
supports the old response format, but also the future response format
which means labels will be list of objects containing both id and label.
> Prepare for upcoming API change regarding hearing.labels

- src/components/Hearing.js
Redux connect excepts "pure" param which needs to be false if we wan't
to edit the component state internally. Such feature is handy during Hearing editing.
Also some code cleanup.
> Enable "unpure" Hearing components

- assets/less/app.less
- assets/less/hel/common.less
- assets/less/hel/fullwidth-hearing.less
- assets/less/hel/hearing-card-list.less
- assets/less/hel/hearing-card.less
- assets/less/hel/variables.less
- package.json
- src/components/FullWidthHearing.js
- src/components/HearingCard.js
- src/components/HearingCardList.js
- src/i18n/en.json
- src/i18n/fi.json
- src/selectors/hearing.js
- src/utils/hearing.js
- src/views/Home.js
- yarn.lock
Fixes #254.
Note: Direct linking to hearings in certain languages is still missing. I wouldn't start implementing that before the API has the translations.
> Open hearings as card grid on front page

- assets/sass/hel/hearing-form.scss
- src/components/admin/HearingFormStep2.js
- src/components/admin/HearingFormStep4.js
- src/utils/hearing.js
> Therefore, closureInfo should not be shown at all in Form step 2 under hearing sections.
✅
> When adding a new Section, it should open up expanded, while collapsing the previous section that the user was working on.
✅
* Fix adding closure info section to hearing ✅
* Fix bottom toolbar styles ✅
> Hearing manager improvements

- package.json
- src/components/RichTextEditor/EditorControls.js
- src/components/RichTextEditor/index.js
- yarn.lock
Removed the formatting tags that are not currently used in hearings. Better keep it simple and just give the user the bare minimum options in creating a hearing. Feel free to point out any required formatting options not present.
One problem here is that `lead` class paragraphs with a separate styling (as used in most hearings) cannot currently be implemented with draft.js, as it strips any class names from the html when parsing it. Made an issue #401 about it, don't know what to do about it at present. Any suggestions on how to format and structure a hearing without css styling are most welcome.
> Some finishes to the simple text editor

- .travis.yml
Node 4.2 is not current by any means anymore.
> Remove Node 4.2 from tested configurations

- .babelrc
- package.json
- server/.babelrc
- server/index.js
- yarn.lock
H/t @hukka :)
It was an old crutch/compatibility shim anyway, no longer necessary.
> Remove babel-plugin-add-module-exports

- assets/sass/hel/carousel.scss
- assets/sass/hel/hearing-page.scss
- src/components/Hearing.js
- src/components/SectionContainer.js
- src/views/Hearing/Header.js
- src/views/Hearing/index.js
- src/views/QuestionView.js
Removed a lot of `container` -wrappers. In general the page could constitute of stacked full browser width sections (that can have a full width background color) and then the content can add a `class="container" or <Grid>` wrapper to limit the content width within the section.
> Style hearing header to have full width bg

- server/Html.js
- server/render-middleware.js
> Solve #317

- deploy/containerize.sh
External PRs are not to be trusted with our docker credentials. Thus we cannot create images for them.
> Do not create docker image for external PRs

- config_dev.toml.example
Without the quotes, the dev server will not start and throw the following error:
```
Error: Error parsing your configuration file: [config_dev.toml]: Expected "'", "'''", "+", "-", "[", "\"", "\"\"\"", "_", "false", "true", "{", [ \t] or [0-9] but "l" found.
```
> Add quotes to default values in dev config example

- src/getRoot.js
- src/scrollToTop.js
Currently the page does not scroll to the top if a page gets
changed. If the user has scrolled down and clicks e.g. navigation
links, the page will stay scrolled down at the point where user
was.
This is a fix to scroll up when using routes to go to a new page.
Found the solution from here:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md
> Fix scrolling issue when routes are changed

- README.md
- __tests__/Hearing/__snapshots__/SectionImage.react-test.js.snap
- assets/sass/kerrokantasi/_hearing-page.scss
- src/components/BaseCommentForm.js
- src/components/Hearing/Comment/index.js
- src/components/Hearing/Section/SectionContainer.js
- src/components/Hearing/Section/SectionImage.js
Add an empty alt tag for images in comments since it's impossible
to give the image an alt tag. This will make the screen readers skip
these images.
Define alt text for main hearing image: If there's no title or caption
provided, use an empty alt tag. If a caption is defined but no title, use
caption. If the title for image is defined, it will be used instead.
Also don't display the image caption element at all if no caption is
provided.
Fixes #707
> Fix some of the image alt texts

- src/routes.js
When the route was placed after the hearing routes it did not find the actual page. It needs to be defined before the hearing routes to make it to work.
> Fix accessiblity info route

- __tests__/Hearing/__snapshots__/HearingContainer.react-test.js.snap
- __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap
- __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap
- __tests__/Home/__snapshots__/FullWidthHearing.react-test.js.snap
- __tests__/__snapshots__/SortableCommentList.react-test.js.snap
- assets/sass/kerrokantasi/variables.scss
- src/components/Header/index.js
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
There are two `<nav>` elements so both need to have a label that defines them. Add aria-labels to both of these elements.
Page nav links did not work correctly and the bootstrap element added `role="presentation"` to the `<li>` elements which causes issues with accessibility. Remove the bootstrap react element and use handwritten version instead.
> Fix main navigation issues

- server/Html.js
Currently, the metadata title when sharing a hearing is fixed to "Kerrokantasi". This doesn't really tell the user who sees the thumbnail what the image and link is about.
I suggest displaying the title of the hearing instead. That way, when shared on facebook and twitter, users see the hearing title.
> Update share metadata title to hearing title

- __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap
- __tests__/__snapshots__/LabelList.react-test.js.snap
- src/components/HearingsSearch.js
- src/components/LabelList.js
When the user clicks a label to filter hearings
with that specific tag/label, change focus to the
select element in the hearing list search.
This is done due that with screen readers the user
loses context when they click one of the labels.
Now the focus will go on the search dropdown element
where these filters are applied.
> Manage focused element after clicking labels

- assets/sass/kerrokantasi/_hearing-subsections.scss
The subhearing box got really tall in Safari. This will fix it
> Fix flex bug with safari on hearing page

- __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap
- src/components/HearingList.js
- src/views/Hearings/index.js
Hearing counter displayed only the first visible hearings, so if there was more than 10 hearings it didn't display the entire amount of the hearings.
> Fix hearing count on hearings list

- __tests__/Hearing/__snapshots__/Header.react-test.js.snap
- config_dev.toml.example
- server/Html.js
- server/getSettings.js
- server/render-middleware.js
- src/components/Hearing/Header.js
- src/config.js
Not every city needs the social media sharing so make it possible to hide them from hearing headers.
By default the social media sharing buttons are shown.
> Add possibility to hide social media sharing via config variable

- __tests__/Hearing/__snapshots__/SectionContainer.react-test.js.snap
- src/components/Header/LanguageSwitcher.js
- src/components/Hearing/Section/SectionContainer.js
The previous issue was that the content did not occure in an intuitive order for desktop users. Since the map was present in the DOM order before other content and it was swithed on the right side of the content with CSS, the reading order changed from right to left. This is bad for the usability.
The fix was to duplicate the map component for mobile and desktop users. For desktop the map element is in the DOM after the content that's on the left and visually it didn't change at all. For mobile users there's the duplicate which will be visible before the main content.
> Switch map element DOM order in hearing section

- assets/sass/kerrokantasi/_common.scss
Turku wanted to have quick way to indicate external links with small
icons. After conversations we decided to include this to global styles.
In this case external links are defined as link that opens to new
target. This way the change was small, and no need to create that to the
editors.
> Display small icon after external link

- src/components/Hearing/Section/SectionContainer.js
- src/components/SortableCommentList.js
- src/views/FullscreenHearing/FullscreenHearingContainer.js
The change resets the `answer` part of a comment after a successful comment has been made. If not done this way, the backend will complain that the user is not allowed to vote twice.
> Comment vote fix

- src/components/Hearing/Comment/index.js
Note that the `handleSubmit`, even if places in the `Comment` component
only handles updates and not creation of comments.
If the image is included when editing a comment it will try to send the image URL and the not the image back to the backend. This will end up in a 400 error where the backend can't interpret the `image` field from the frontend.
Since there is no support for removing or editing just the image of a comment, this is the fastest way to let people edit comments with images at this point. In the future, if image replacing or removing is added, then this needs to be refactored to use an actual image.
> Do not include images when editing comments

- server/bundler.js
- src/components/Header/index.js
Added aria-label for navbars login and high-contrast buttons. Also fixed yarn dev command.
> #784 Alt-text must be added to the loggin button in mobile version

- cities/helsinki/i18n/en.json
- cities/helsinki/i18n/fi.json
- cities/helsinki/i18n/sv.json
Added more informative headerLogoAlt translations for screen reader
> #782 Text alternative for Helsinki logo, which acts as a link, should be "Go to the home page"

- src/components/admin/HearingEditor.js
Previously all errors were visible even after successfully saving a hearing.
refs. KER-31
> Clear hearing form errors

- assets/sass/kerrokantasi/_commentlist.scss
- src/components/Hearing/Comment/index.js
- src/components/SortableCommentList.js
- src/utils/notify.js
- Opening a link that has a comment URL fragment e.g. `/hearing-slug#comment-{id}` highlights that comments and focuses user's window on the comment, even if it is a subcomment.
- Add a button to the top-right of a comment to copy a link to the comment, which is visible only to comment moderators
- Highlight flagged comments for organisation moderators
refs: KER-29
> Allow copying a direct link to a hearing comment

- server/Html.js
- src/utils/commonUtils.js
- src/views/AccessibilityInfo/index.js
- src/views/Hearing/HearingContainer.js
- src/views/Hearings/index.js
- src/views/Home.js
- src/views/Info/index.js
Use `react-helmet` to manage OGP tags.
* remove hearing meta tag declarations in `Html.js`
* let views manage their own ogp tags
* this provides multi language support and more dynamic labeling for hearings
> OGP meta tag modificaitons

- src/routes.js
`react-router-dom` provides the `<Route />` component which in that version (`^4.3.1`) requires the `component` props as a function type. Therefore there is red warnings in browser's console.
```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
in Route (created by Routes)
in Routes (created by App)
in main (created by App)
in div (created by App)
in IntlProvider (created by App)
in App (created by Connect(App))
in Connect(App) (created by Route)
in Route (created by withRouter(Connect(App)))
in withRouter(Connect(App))
in ScrollToTop (created by Route)
in Route (created by withRouter(ScrollToTop))
in withRouter(ScrollToTop)
in Router (created by ConnectedRouter)
in ConnectedRouter
in r
in Provider
in div
```
* this could be …
> fix route component prop type to function instead of object

- Dockerfile
Dockerfile: modify the build process such that the resulting image can run in Openshift. Essentially make sure that directories that need to be written are owned by group 0 and writable by that group. Image is also changed to run with said group 0.
> Modify container to run on Openshift, with limited write permissions

- src/api.js
- src/components/CommentReportModal/CommentReportForm.js
Bugfix in cases where there is path provided in config for API base url. See example below.
```js
const base = "http://localhost:8000/test"
const url_1 = new URL(base + "/path");
const url_2 = new URL("/path", base);
```
```js
url_1 URL {
href: 'http://localhost:8000/test/path',
origin: 'http://localhost:8000',
protocol: 'http:',
username: '',
password: '',
host: 'localhost:8000',
hostname: 'localhost',
port: '8000',
pathname: '/test/path',
search: '',
searchParams: URLSearchParams {},
hash: '' }
url_2 URL {
href: 'http://localhost:8000/path',
origin: 'http://localhost:8000',
protocol: 'http:',
username: '',
password: '',
host: 'localhost:8000',
hostname: 'localhost',
port: '8000',
pathname: '/path',
search: '',
searchParams: URLSearchParams {},
hash: '' }
```
> if base-url contains path it would be ignored in URL constructor

- server/getSettings.js
This setting was missing from the list of ones to be picked up by nconf.
> Allow configuring Helsinki-style API-token endpoint location

- package.json
Add `yarn coverage` script that runs `jest` tests and outputs coverage report.
> add coverage script for cicd

- src/components/admin/HearingFormStep4.js
Requested feature so that picking an end date defaults to end of day (23:59:59) instead of start of day (00:00:00). [react-datetime](https://github.com/arqex/react-datetime/#react-datetime) didn't seem to provide any good way of doing this. Therefore here's a proposed solution where we always convert an end datetime that isSame as start of day into end of day. An unfortunate side effect is that it is no longer possible to select "00:00" as the end time, the earliest possible time for the day is now "00:01". 
Attempting to manually input "klo 00.00" will convert into "klo 23.59".
> Convert end date 00:00 to 23:59

- src/utils/matomo.js
fix: matomo.js expects different tracker url compared to piwik.js
Felt like parametrisizing this part would be bit over configuring this so created a simple if-else variable.
> fix: matomo.js expects different tracker url compared to piwik.js

- config_dev.toml.example
- server/getSettings.js
- src/utils/matomo.js
… because configMap does not support Array variables, instead parsing a string into array.
> KER-196: changed matomo_domains to string

- README.md
This PR adds instructions for using a local API and Tunnistamo instances for development with docker.
> KER-226 | Add instructions for using local API and Tunnistamo

- src/actions/hearingEditor.js
- src/components/admin/HearingEditor.js
- src/middleware/hearingEditor.js
- src/reducers/hearingEditor/contactPersons.js
- src/reducers/hearingEditor/index.js
- src/views/Hearing/HearingContainer.js
Fetch contact person data when mounting `<HearingEditor />` component. The parent `<HearingContainer />` does not need the data from `/v1/contact_person/` endpoint.  Eg. fetch the data from endpoint `/v1/contact_person/` only when the user is admin or editor of the hearing.
* separate the `/v1/contact_person/` api call from the bundled dispatch method `fetchHearingEditorMetaData()`
* perform this dispatch in `<HearingEditor />` constructor
> Separate contact person fetching to different dispatch method

- __tests__/HearingEditor/HearingEditor.react-test.js
Fix failing test
```
Summary of all failing tests
FAIL __tests__/HearingEditor/HearingEditor.react-test.js
● HearingEditor › validateHearing
TypeError: fetchEditorContactPersons is not a function
66 |     };
67 |     const { fetchEditorContactPersons } = this.props;
> 68 |     fetchEditorContactPersons();
|     ^
69 |   }
70 |
71 |   toggleCommentReports() {
at new fetchEditorContactPersons (src/components/admin/HearingEditor.js:68:5)
at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:784:26)
at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:643:41)
at renderElement (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:759:44)
at fn …
```
> mock fetchEditorContactPersons function provided as a prop to component

- src/middleware/language.js
Hotfix for a bug: [KER-277](https://helsinkisolutionoffice.atlassian.net/browse/KER-277)
So, getting language from query string didn't work. There was a bug on middleware that parses query string -> now fixed
[KER-277]: https://helsinkisolutionoffice.atlassian.net/browse/KER-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KER-277 Fix language from query string bug

- __tests__/InternalLink.react-test.jsx
- src/App.jsx
- src/components/Hearing/Section/SectionContainer.jsx
- src/components/InternalLink.jsx
Hotfix for a bug [KER-276](https://helsinkisolutionoffice.atlassian.net/browse/KER-276)
#Problem:
Internal links didn't work, but only in one place. I found out that the only working link didn't use the project's `InternalLink` -component but `react-anchor-link-smooth-scroll` npm component. Our `InternalLink` -component uses `react-router-hash-link` npm component under the hood. 
#Fix:
I changed `InternalLink` to use `react-anchor-link-smooth-scroll`
#Notes:
I searched for the reason why `react-router-hash-link` didn't work and found out from their [document](https://www.npmjs.com/package/react-router-hash-link) that this component works only with `ReactRouter`'s `BrowserRouter`, which we are not using
[KER-276]: https://helsinkisolutionoffice.atlassian.net/browse/KER-276?atlOrigin=eyJpIjo …
> KER-276 Fix internal links

- README.md
This PR fixes the instructions for the Tunnistamo OIDC client setup. Django admin login should work with a local Tunnistamo instance with the updated instructions.
> KER-280 | Fix intructions for django admin tunnistamo login

- assets/sass/kerrokantasi/_common.scss
- cities/helsinki/assets/sass/hel/_hearing-page.scss
- src/components/ProgressBar.jsx
- src/components/QuestionResults.jsx
- src/components/admin/QuestionForm.jsx
----------------------------------------------------------------------------------------------
Reason behind change:
Removing old, deprecated React-bootstrap library from use and switching to HDS components. HDS did not offer suitable component for replacing the ProgressBar so instead created a custom component to solve this need.
> feat: New progress bar to replace old bootstrap one

- server/getSettings.js
Fix for OPENID_SCOPE not getting properly read from env variables.
> KER-291 fix OPENID_SCOPE

- .github/workflows/ci.yaml
Release-please might create commit messages with longer lines than the limit of 72 chars, for example https://github.com/City-of-Helsinki/kerrokantasi-ui/commit/26307af785dd2d5769eac38a05f4bd2019194a9c. That shouldn't be a big issue. However, then [commitlint makes CI action fail](https://github.com/City-of-Helsinki/kerrokantasi-ui/actions/runs/8844826904/job/24287473208), which is not nice.
So disabled running commitlint against the main branch. When a commit is in the main branch it cannot be changed anyway 🙂
> ci: stop running commitlint against main branch

- src/actions/__tests__/hearingEditor.test.jsx
- src/actions/hearingEditor.js
- src/components/admin/HearingEditor.jsx
- src/utils/__tests__/hearingEditor.test.js
- src/utils/hearingEditor.js
TL;DR:
- Rename `cleanHearing` -> `prepareHearingForSave`
- Remove IDs from *all* objects when preparing hearing for saving, not just the section
- Prepare hearing only when creating a new hearing (either a fresh hearing or a copy of an existing hearing)
- Add new `reference_id` field in files/images on save
- Mark freshly uploaded files with `isNew`
- Don't assign uploaded files for hearing before saving
---
The "save as copy" action relies on some rather strange back-end logic where removing the ID is required only on some instances and, on the other hand, requires an ID in files. However, if you were creating a hearing the first time with a file uploaded to it, it causes problems.
To somewhat solve this problem, [a new field called `reference_id` can now be used with files and …
> KER-351: Fix save hearing as copy

- src/components/admin/HearingEditor.jsx
Opening hearing editor can cause a blank page. This seems to happen if meta data has not yet been fully loaded before toolbar.
> fix: hearing toolbar wait for metadata KER-345

- src/selectors/hearingEditor/__tests__/index.test.js
- src/selectors/hearingEditor/index.js
getPopulatedHearing selector can end up in error if hearing.contact_persons is undefined. Added ternary check for if value is undefined, although I was not actually able to reproduce the bug on my local machine.
> KER-378 Hearing editor selector getPopulatedHearing check

- src/components/OverviewMap.jsx
OverviewMap should set content as html instead of plain string
> KER-260 OverviewMap set popup content as html

- assets/sass/kerrokantasi/_commentlist.scss
- assets/sass/kerrokantasi/_common.scss
- assets/sass/kerrokantasi/_fullwidth-hearing.scss
- assets/sass/kerrokantasi/_hearing-card.scss
- assets/sass/kerrokantasi/_hearing-list.scss
- assets/sass/kerrokantasi/_hearing-page.scss
- assets/sass/kerrokantasi/_hearing-subsections.scss
$text-muted css variable does not have enough contrast agains white background, replacing all occurances with HDS variable --color-black-60.
Before:
After:
> KER-377 Replace low contrast text-muted css variable

- package.json
Later nodejs versions default to using 50% of container allocated memory. This change adds an environment variable that can be used to override the default behaviour.
Refs: KER-382
Related: https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/9586
> fix: allow setting nodejs --max-old-space-size via environment variable

- assets/sass/kerrokantasi/_hearing-page.scss
Fixing contacts not stacking on mobile viewport sizes.
> fix: fixed contacts not stacking on mobile sizes

- e2e/tests/pages/hearing.spec.js
- src/components/admin/HearingEditor.jsx
The hearingEditor caused an error due to hearing not being initialized before save action.
> fix: fixed dependency array not having variables that require init

- src/components/admin/HearingFormStep1.jsx
Hearing slug onChange argument should be event.
> fix: hearing slug onChange KER-422

- src/actions/hearingEditor.js
- src/components/admin/HearingFormStep5.jsx
- src/components/admin/Phase.jsx
- src/components/admin/Project.jsx
- src/components/admin/__tests__/HearingFormStep5.test.jsx
- src/components/admin/__tests__/Phase.test.jsx
- src/reducers/hearingEditor/hearing.js
Fixing hearing project fields, which are currently overall broken.
> KER-422 hearing projects fixes

- src/components/admin/HearingFormStep1.jsx
Combobox uses label as default key, which can cause problems with duplicate items.
> fix: labels dropdown key field KER-422

- src/components/Hearing/Comment/index.jsx
- src/components/admin/SectionForm.jsx
- src/routes.jsx
Comments have yellow color to the border if they are made by admin.
When creating hearing, enabling commenting for strong auth users is now again behind config value.
> fix: fixes to commenting colors and options

- src/App.jsx
- src/components/CookieBar/CookieBar.jsx
- src/components/Footer.jsx
- src/components/Header/Header.jsx
- src/components/Header/__tests__/Header.test.jsx
- src/getRoot.jsx
- src/hooks/useAuth.js
KK used to only direct to browser default language login page, that has now been fixed.
This required some changes to where the current language is stored and how it is used.
Further review on how the translations have been implemented would be beneficial.
> fix: fixed login to use current language

- src/components/admin/HearingFormStep3.jsx
fix: hearingFormStep3 add marker file
> fix: hearingFormStep3 add marker file KER-449

- src/utils/constants.jsx
Missed the .geojson filetype from accepted filetypes for geojson map.
> fix: increased valid filetypes for geojson

- src/components/admin/SectionForm.jsx
Fix to fileupload not functioning as it was intended and removing / reuploading images on edit.
> fix: fixed fileupload not working as intended

- e2e/tests/pages/hearing.spec.js
- src/actions/hearingEditor.js
Editing hearing that was unpublished caused sections to have empty id's when sent to backend which in return caused new sections to be generated for hearing.
> fix: hearing saveAndPreview fix for existing hearings

- e2e/constants.js
- e2e/tests/login.spec.js
- e2e/utils.js
Add Login E2E test.
Branched from [KER-404 Vite](https://github.com/City-of-Helsinki/kerrokantasi-ui/tree/feat/KER-404-vite)
Pipelines changes: https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/11175
[KEH-98](https://helsinkisolutionoffice.atlassian.net/browse/KEH-98)
[KEH-98]: https://helsinkisolutionoffice.atlassian.net/browse/KEH-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add login e2e test KEH-98

- e2e/tests/login.spec.js
login.spec.js should require both `TEST_USER_EMAIL` and `TEST_USER_PASSWORD` and not just one.
> fix: login test requires both env variables KEH-98

- src/components/CommentFormMap/CommentFormMap.jsx
- src/components/Hearing/Comment/index.jsx
- src/components/Hearing/HearingMap.jsx
- src/components/OverviewMap.jsx
- src/components/UserComment/UserComment.jsx
- src/components/admin/HearingFormStep3.jsx
Fixing react-leaflet-draw rectangle bug.
> fix: leaflet-draw rectangle bug

- src/__tests__/App.test.jsx
- src/hooks/__tests__/useNotifications.test.jsx
- src/hooks/useNotifications.js
Notifications had wrong name for alerts (had used warnings).
> fix: corrected notification type names
