assets/app.less, src/views/Hearing/index.js
=> Make Sidebar visible at all time when scrolling through an Hearing

.travis.yml, assets/app.less, assets/hearing-page.less, server/render.js, src/components/Comment.js, src/components/CommentForm.js, src/components/CommentList.js, src/components/LabelList.js, src/components/OverviewMap.js, src/components/Scenario.js, src/components/ScenarioList.js, src/components/SocialBar/Facebook.js, src/components/SocialBar/Twitter.js, src/components/SocialBar/index.js, src/components/SocialBar/utils.js, src/i18n/fi.json, src/views/Hearing/index.js, test/SocialBar.js
=> Social Sharing

package.json, src/components/Header/index.js
Just minorish upgrades here (and the required changes for react-bootstrap).
Left babel/isparta major semver updates be for the time being.
=> Upgrade safe dependencies

server/auth.js
Not that this commit does much, but things seem to work now...
Refs #112
=> Fix authentication, hopefully

src/actions/index.js, src/views/Hearing/index.js
=> Pass preview query param to backend API

src/views/Hearing/Sidebar.js
=> Don't show link to scenarios if there are none

assets/hearing-page.less, package.json, src/components/Section.js, src/utils/section.js, src/views/Hearing/index.js
Added Classnames v2.2.3
Added closure info section handling. In case closure info section exists, it is rendered as the topmost
section with yellow background.
=> Tune closure info

src/components/Section.js, src/components/SectionList.js, src/i18n/en.json, src/i18n/fi.json, src/utils/section.js, src/views/Hearing/Sidebar.js, src/views/Hearing/index.js
The sections are grouped by type. Sidebar contains a link to each
group. The groups are ordered based on the ordering of their most
lowest ordered section.
Added also missing translation of "no comments available".
=> Dynamic section type

src/components/OverviewMap.js
Also removed obsolete lat/lng handling.
Fixes #140
=> Fit overview map to hearing bounds

assets/less/hel/hearing-page.less, src/views/Hearing/Sidebar.js
* Move social media above map
* Add specifier classes to sidebar elements
=> Change order of sidebar elements on hearing page

src/components/Header/index.js, src/config.js
=> Only use Finnish for the time being.

src/components/BaseCommentForm.js, src/createStore.js, src/reducers/index.js
According to issue #174 preserved text in comment box is causing
bad usability.
After comment submit remove the text
Refs: #174
=> Clear message text field after submit

src/actions/index.js, src/components/Comment.js, src/components/HearingList.js, src/components/Section.js, src/i18n/fi.json, src/utils/section.js, src/views/Hearing/Sidebar.js, src/views/Hearing/index.js, test/test-hearing-data.json
- introduction section is renamed to main
- hearing images are converted to main section images, hearings have
also main_image field within their data
- hearing comments are converted to main section comments
ATTENTION requires the corresponding changes to be deployed on the backend!!
=> Changes needed because of backward incompatible API changes

src/actions/index.js
Refs City-of-Helsinki/kerrokantasi@444cd2a81
=> Expect Hearings to be paginated in the backend

src/components/Section.js, src/components/SectionList.js, src/utils/section.js, src/views/Hearing/index.js
=> Allow sections be not commentable when the hearing isn't

src/components/OverviewMap.js
Finetune map views with better params.
Refs: #204
=> Looser map bounds

assets/less/app.less, assets/less/hel/common.less, assets/less/hel/fullscreen-map-plugin.less, assets/less/hel/hearing-page.less, src/App.js, src/actions/index.js, src/components/FullscreenHearing.js, src/components/FullscreenPlugin.js, src/components/Hearing.js, src/components/HearingList.js, src/components/OverviewMap.js, src/components/Section.js, src/i18n/fi.json, src/reducers/hearing.js, src/routes.js, src/utils/hearing.js, src/views/Hearing/Sidebar.js, src/views/Hearing/index.js
Fullscreen map (seems to have unnecessary scrollbar still)
Sidebar "to fullscreen" button
=> Fullscreen map

src/components/Comment.js, src/components/Hearing.js
=> Refactor hearing component

src/components/CommentList.js
Cleaner code to reduce complaints from eslint.
=> Finetune code to appease eslint

__tests__/hearingUtils.js, __tests__/sectionUtils.js, src/utils/hearing.js, src/utils/section.js
These utilities provide common functionality often needed when working
with Hearings and Sections.
=> Add utility functions for easier Hearing and Section handling

assets/less/hel/common.less
**Mobile**
**Desktop**
Refs: #186
=> Fix label spacing on hearing page

assets/less/app.less, assets/less/hel/fullwidth-hearing.less, assets/less/hel/variables.less, src/components/FullWidthHearing.js, src/selectors/hearing.js, src/views/Home.js
=> Show most popular open hearing on home page

assets/less/hel/hearing-page.less
=> Make comment textarea 6 rows tall

__tests__/__snapshots__/LabelList.react-test.js.snap, package.json, src/components/HearingList.js, src/components/HearingsSearch.js, src/components/LabelList.js, src/views/AllHearings.js, yarn.lock
=> Link displayed labels to search page with selected label

src/App.js, src/actions/index.js, src/config.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/reducers/language.js, src/utils/getMessage.js, src/utils/notify.js
=> Add localized error messages

assets/sass/app.scss, assets/sass/hel/alertify.scss, assets/sass/hel/hearing-form.scss, src/components/Hearings/CreateHearingButton.js, src/components/admin/HearingToolbar.js, src/index.js, src/utils/notify.js
Maybe an overkill with icons and variating alert styles, but let's try this.
=> Revise toolbar status styles

assets/sass/hel/hearing-page.scss, src/components/Section.js
* Do not show header or lead elements on closure info box if they have no content
* Fix closure info styles accordingly
=> Don't add empty elements. Fix styles

assets/sass/hel/forms.scss, package.json, src/components/RichTextEditor/EditorControls.js, src/components/RichTextEditor/index.js, src/components/admin/ContactModal.js, src/components/admin/HearingForm.js, src/components/admin/HearingFormStep1.js, src/components/admin/HearingFormStep4.js, src/components/admin/LabelModal.js, src/components/admin/SectionForm.js, src/components/forms/MultiLanguageTextField.js, yarn.lock
First working version of the rich text editor built with Draftjs. Fixes #278.
=> Introduce a rich text editor for section content

assets/sass/hel/common.scss, assets/sass/hel/footer.scss, assets/sass/hel/fullwidth-hearing.scss, assets/sass/hel/hearing-card.scss, assets/sass/hel/hearing-list.scss, assets/sass/hel/hearing-page.scss, assets/sass/hel/home.scss, assets/sass/hel/navigation.scss, assets/sass/hel/variables.scss, package.json, src/components/Header/index.js, src/components/HearingList.js, src/components/SortableCommentList.js, src/views/Home.js, yarn.lock
- Update to hel-bootstrap-3@1.0.0-beta.4
- Use koros and colors on the front page
=> Use new hel-bootstrap-3 styles

conf/webpack/common.js
This slims down the generated bundle, making it faster to compile, download and parse.
=> Only bundle English/Finnish/Swedish Moment.js locales

src/actions/index.js, src/api.js, src/components/HearingList.js, src/reducers/hearingLists.js, src/views/Hearings/index.js
=> Feature/hearing list pagination #406

package.json, server/Html.js, src/actions/index.js, src/createStore.js, src/i18n/en.json, src/i18n/fi.json, src/index.js, yarn.lock
=> Feature/sentry integration #381

server/.babelrc
Fixes regression from accaf37, oops
=> Add .babelrc to server/

README.md, server/Html.js, src/App.js, src/components/Footer.js, src/utils/notify.js, src/views/Home.js
> petteri [19:52]: Hoi kuulkaas, Heli Rantanen (joka oli mukana kun hommaa käynnisteltiin) tokaisi että *Kerrokantasi* oli alkuperäinen kirjoitusasu, samoin kuin Kerrokartalla, joten mennään sillä. THE END.
=> Unify spelling to Kerrokantasi everywhere

complexity.eslintrc.js, package.json
Partially re the conversation in Slack - adhering to these rules (or even tighter variants of them) might lead to more maintainable code.
=> Add Eslint ruleset and package command for checking code complexity

conf/webpack/common.js, conf/webpack/dev.js, conf/webpack/prod.js, src/createStore.js
`dist/` is now 13.2% smaller than before.
```
(master) $ du -k dist
3260	dist
(HEAD) $ du -k dist
2880	dist
```
=> Further bundle size emslimmening

assets/sass/hel/carousel.scss, assets/sass/hel/hearing-page.scss, src/components/Carousel.js, src/components/Hearing.js, src/components/SectionContainer.js
- Make carousel its own section
- improve responsiveness
- include map in the carousel
- add indicator for current (Active) section. @jonnetanninen : this needs functionality. Now highlights the center slide, not the currently active view.
- use default image on imageless sections
=> Subnav carousel styling

src/components/admin/HearingForm.js, src/reducers/hearingEditor/sections.js
=> Fix #477 & #482

__tests__/Hearing/__snapshots__/Hearing.react-test.js.snap, __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap, __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, __tests__/Home/__snapshots__/FullWidthHearing.react-test.js.snap, __tests__/__snapshots__/SortableCommentList.react-test.js.snap, src/actions/hearingEditor.js, src/components/admin/HearingEditor.js, src/components/admin/HearingForm.js, src/components/admin/HearingFormStep2.js, src/components/admin/SectionForm.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/reducers/hearingEditor/hearing.js, src/utils/hearingEditor.js
Solves #513.
This was (fairly) easy version to implement this functionality. If we want this to actually work with drag n drop, that would take a lot more work. I suggest we use this or some other form of buttons for reordering to save massive amount of work.
=> Add functionality for reordering sections

src/components/SortableCommentList.js
Removes console warnings about invalid DOM as per https://github.com/yahoo/react-intl/issues/286#issuecomment-236348944
=> Fix warnings about bad DOM in SortableCommentList

assets/sass/app.scss, assets/sass/hel/hearing-form.scss, src/components/admin/HearingForm.js, src/components/admin/HearingFormStep1.js, src/components/admin/HearingFormStep2.js, src/components/admin/HearingFormStep3.js, src/components/admin/SectionForm.js
Revise hearing edit form button placement and form typography for better usability and consistency. Based on user test feedback.
=> Restyle hearing edit form - fix #540

__tests__/Hearing/__snapshots__/Hearing.react-test.js.snap, __tests__/QuestionView/__snapshots__/SectionContainer.react-test.js.snap, __tests__/__snapshots__/SortableCommentList.react-test.js.snap, src/components/Header/LanguageSwitcher.js, src/components/SortableCommentList.js, src/createStore.js, src/middleware/language.js, src/views/Hearing/Header.js
Solves #510. Should be merged only after PR #478 has been merged.
=> Solve #510, add ui language selection to url

assets/sass/hel/carousel.scss, src/components/Carousel.js
=> Solve #518, Add comment count to horizontal navbar section cards

src/components/Carousel.js
=> Fix #524, Refocus slider on route change

src/components/admin/HearingForm.js
Fixes editor saving problems for now by forcing blur before saving can happen
=> Fixes hearing editor saving problems

src/views/Hearing/HearingContainer.js
=> Fix #566, Reload hearing after receiving user to allow refreshing hearing drafts

src/components/admin/HearingForm.js, src/components/admin/HearingFormStep2.js
Newer version of react-bootstrap handles panel headers and body differently. Panels fixed for new version here.
=> Fix admin form collapsing panels Fix #581

__tests__/Hearing/__snapshots__/Header.react-test.js.snap, __tests__/__snapshots__/LabelList.react-test.js.snap, src/components/Hearing/Header.js, src/components/HearingList.js, src/components/LabelList.js, src/views/Hearing/HearingContainer.js, src/views/Hearings/index.js
=> Solve #429 correct language for labels

src/components/OverviewMap.js
=> Fix #569, attempted to load infinite number of tiles

src/views/Hearings/index.js, src/views/Home.js
=> #530, add new hearing button to home page

__tests__/Home/__snapshots__/HearingCard.react-test.js.snap, src/components/FullWidthHearing.js, src/components/HearingCard.js
And make default image check on hearingCard more elegant.
=> Add default image on imageless fullwidth hearing.

server/Html.js
=> Fix server

__tests__/Home/__snapshots__/Home.react-test.js.snap, src/actions/index.js, src/components/admin/HearingToolbar.js, src/i18n/en.json, src/utils/notify.js, src/views/Home.js
Solves #628 & #629 & #630 & #631
=> Fix #628 & #629 & #630 & #631

assets/sass/hel/hearing-card.scss
=> fix navbar show incorrectly in mobile

src/components/Header/index.js
=> solved #395

src/components/Comment.js
=> solved #621

src/components/admin/SectionForm.js, src/reducers/hearingEditor/sections.js
make new question appears at the top of questions list. And fix exception throwed during new hearing creation
=> fix reducers in poll admin, and improve UI

src/views/Hearing/HearingContainer.js, src/views/NewHearing/NewHearingContainer.js
=> fix no project fetched during new hearing creation

__tests__/Hearing/__snapshots__/Header.react-test.js.snap, src/components/Hearing/Header.js
=> center and set default pointer for active phase

__tests__/Hearing/__snapshots__/Header.react-test.js.snap, src/components/Hearing/Header.js
=> add conditioning to fix carousel scrolling

.gitmodules, README.md, deploy/fetch_plugins.js, package.json, src/components/PluginContent.js, src/config.js, src/shared_config.json, yarn.lock
This adds a script and a NPM command for fetching plugins. This makes it possible to always fetch the latest plugins, without needing to update the kk-ui repository itself (I understand submodules lock the versions). It also allows fetching the plugins to an arbitrary path.
I also added some documentation to the README about the existence of plugins. That still needs some cleanup. Information is welcome.
The list of plugins is in the script still. Would that need to be fetched from somewhere else as well?
=> Add npm script fetching plugins

__tests__/Home/__snapshots__/Home.react-test.js.snap, src/components/OverviewMap.js
#Fixes error with boudingRectClient
=> fixing errors for calculating rect client

src/actions/hearingEditor.js, src/components/admin/HearingEditor.js, src/components/admin/HearingForm.js, src/components/admin/HearingFormStep2.js, src/components/admin/QuestionForm.js, src/components/admin/SectionForm.js, src/reducers/hearingEditor/sections.js
=> removing a question

__tests__/Home/__snapshots__/Home.react-test.js.snap, conf/webpack/dev.js, conf/webpack/prod.js, package.json, server/bootstrap.js, server/getSettings.js, src/components/OverviewMap.js, src/components/admin/HearingFormStep3.js, test-utils.js, yarn.lock
#662 Webpack and middle wares upgraded with slight configuration modification
=> upgrading webpack and middlewares and linting and update test

assets/sass/kerrokantasi/variables.scss
Make the whitelabel variables overwritable by adding the default flag for them
=> Add default flag for all the whitelable sass variables

src/actions/index.js
Minor change to add sentry message for the case when posting receives 400 status.
=> Sentry message for in case of bad request

assets/urls.json, cities/helsinki/assets/urls.json, src/components/Footer.js, src/views/Home.js
Feedback is a better term for this since the url can
be anything and this url is used for feedback.
=> Change "mailto" to "feedback" in url config

__tests__/Hearing/__snapshots__/HearingContainer.react-test.js.snap, __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap, __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, __tests__/Home/__snapshots__/FullWidthHearing.react-test.js.snap, __tests__/__snapshots__/SortableCommentList.react-test.js.snap, cities/helsinki/i18n/accessibility-info/accessibility.en.md, cities/helsinki/i18n/accessibility-info/accessibility.fi.md, cities/helsinki/i18n/accessibility-info/accessibility.sv.md, config_dev.toml.example, server/Html.js, server/getSettings.js, server/render-middleware.js, src/components/Footer.js, src/config.js, src/i18n/accessibility-info/accessibility.en.md, src/i18n/accessibility-info/accessibility.fi.md, src/i18n/accessibility-info/accessibility.sv.md, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/routes.js, src/views/AccessibilityInfo/index.js
This page is not displayed by default and it can be displayed by changing the config variable.
=> Add accessibility info/statement page

src/components/Hearing/Header.js
=> Fix OverlayTrigger of not having only one child element

__tests__/Hearings/__snapshots__/HearingList.react-test.js.snap, __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, src/components/HearingList.js, src/views/Hearings/index.js
Default to value 0 instead of undefined
=> Fix hearing count value of undefined

.dockerignore, Dockerfile, README.md, assets/urls.json, package-lock.json, server/getSettings.js, yarn.lock
- Made changes to Dockerfile in order to serve kerrokantasi-ui express server inside a docker container.
- Added .dockerignore file with basic options
- Modified README.md to contain docker instructions
=> New docker configuration for kerrokantasi-ui

src/components/Hearing/Section/SectionContainer.js
All comment messages should be visible all the time for everyone although commenting is only allowed for the registered
=> Fix the visibility of commenting and voting

__tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, server/bundler.js, src/components/HearingsSearch.js, src/views/Hearings/index.js
- When using screen reader and keyword is clicked on a hearing, hearings page focuses on page title
=> #785 focus to the beginning of all hearings page

__tests__/Hearing/__snapshots__/HearingContainer.react-test.js.snap, __tests__/Hearings/__snapshots__/HearingList.react-test.js.snap, __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, __tests__/__snapshots__/SortableCommentList.react-test.js.snap, src/components/Header/index.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Added aria-label for Navbar.Toggle component in header component. Also updated test snapshots
=> #783 In mobile version, "area-expanded" attribute and better alt-text must be added to toggle navigation button

__tests__/LanguageSwitcher-test.js, assets/sass/kerrokantasi/_navigation.scss, src/components/Header/LanguageSwitcher.js
Moved languages away from dropdown to a inline list and updated LanguageSwitcher tests
=> #777 Enable non-Finnish speakers to change language settings from their screen readers

src/App.js, src/components/FullWidthHearing.js, src/components/Hearing/Section/SubSectionsList.js, src/components/HearingCard.js, src/components/HearingList.js, src/components/MouseOnlyLink.js
closes #779 
skipToMainContent button onClick focuses to main-container element
closes #780 
Added altText property for MouseOnlyLink component to display alt attribute for image
=> #779 "Suoraan sisältöön" link should move focus to the main content & #780-Thubnail image should have the same all-text as full-sized image

src/components/Header/index.js, src/components/OverviewMap.js
Added key attribute to OverviewMap and header to prevent unique key warning
=> #810 Add key attribute for multipolygons in OverviewMap component

.travis.yml, __tests__/map-test.js, cities/helsinki/assets/urls.json, src/components/BaseCommentForm.js, src/components/OverviewMap.js, src/components/admin/HearingFormStep3.js, src/utils/map.js, yarn.lock
Added support for language specific map tiles. Also added highContrastRasterMapTiles url to helsinki city urls.json.
=> #797 Use Swedish map tiles in Swedish UI and English in English UI

.travis.yml, src/components/admin/HearingFormStep4.js
Closure info content is now saved on create and edit
=> #531 Fix: edits to hearing closing announcement are not saved

cities/helsinki/assets/urls.json
=> Use Turku map style when high-contrast setting is enabled

src/components/Hearing/Section/SectionContainer.js, src/components/RichTextEditor/Image/ImageModal.js, src/components/RichTextEditor/index.js
=> Hearing section image rendering fix, alt text

assets/js/piwik.js, cities/helsinki/assets/js/piwik.js, src/utils/cookieUtils.js
=> Change Matomo analytics to use digitaiiris

package.json, src/components/admin/HearingForm.js, src/components/admin/HearingFormStep2.js, yarn.lock
Remove `react-collapse` from requirements as its no longer used anywhere.
=> Use new hearing collapse implementation

assets/sass/kerrokantasi/_commentlist.scss, src/components/Hearing/Comment/index.js
- Style deleted comments slightly differently
- Hide interactable links from deleted comments
refs. KER-16
related: https://github.com/City-of-Helsinki/kerrokantasi/pull/362
=> Deleted comments

config_dev.toml.example, server/Html.js, server/render-middleware.js, src/components/admin/SectionForm.js, src/config.js
=> Setting for Strong Authentication commenting option

Dockerfile, README.md, compile/compile.js, compile/index.js, package.json, server/bootstrap.js, server/bundler.js
Precompile js bundle to docker image instead of building it on server start to improve the container boot time
refs: KER-45
=> Compile js bundle in build step

src/components/Hearing/Comment/index.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
=> Localise deleted comment messages

src/components/Hearing/Section/SectionContainer.js
=> Open Hearing Details on page load on desktop only

compile/compile.js, server/bundler.js
Save bundle src only after compilation is finished
=> Fix bundle compilation sometimes failing due to race conditions

assets/sass/kerrokantasi/_cookiebar.scss, src/components/ContactCard.js, src/components/Header/index.js
=> Small visual changes

package.json, yarn.lock
-----------------------------------------------------------------------------------------------
1. package.json 
* `react-test-utils` riippuvuuden poistaminen
2. yarn.lock
* `yarn` ylläpitämä lock-tiedosto
=> Toimimattomien ja käyttämättömien riippuvuuksien siivoaminen

__tests__/Hearing/__snapshots__/HearingContainer.react-test.js.snap, __tests__/Hearings/__snapshots__/Hearings.react-test.js.snap, __tests__/Home/__snapshots__/Home.react-test.js.snap, src/utils/commonUtils.js
Update the test to contain snapshot data according to new metadata fields
=> update test snapshots to contain current metadata

src/components/HearingList.js
=> KER-58: Fixes the wordings to use correct division of time

__tests__/LanguageSwitcher-test.js, assets/sass/kerrokantasi/_navigation.scss, src/components/Header/LanguageSwitcher.js, src/components/Header/index.js, yarn.lock
[https://helsinkisolutionoffice.atlassian.net/browse/KER-153](https://helsinkisolutionoffice.atlassian.net/browse/KER-153)
Kielen valinta yläpalkissa on korvattu HDS buttonilla, ikoneilla ja pudotusvalikolla. Voi olla, että pitää ensin katselmoida ja mergata tämä ja sitten [KER-154](https://helsinkisolutionoffice.atlassian.net/browse/KER-154) ja sen jälkeen hieman hienosäätää. 
Kun uusi [HDS Navigation](https://hds.hel.fi/components/navigation) -komponentti pian valmistuu (HDS versioon 3.0.0), se tulee korvaamaan koko yläpalkin. 
[KER-154]: https://helsinkisolutionoffice.atlassian.net/browse/KER-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KER-153 use HDS Select for the language switcher

src/components/CookieBar/CookieBar.js, src/components/Footer.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json, src/routes.js, src/utils/cookieUtils.js, src/views/CookieManagement/index.js, src/views/Info/index.js
A way to manage cookies after modal is no longer shown as required.
=> KER-207: Added cookie management page

__tests__/Hearing/__snapshots__/HearingContainer.react-test.js.snap, __tests__/__snapshots__/SortableCommentList.react-test.js.snap, src/components/BaseCommentForm.js, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
- Registered user (not admin) can optionally write their comment anonymously
- Refactoring BaseCommentForm into function component
=> KER-195 Registered user can comment anonymously

config_dev.toml.example, server/Html.js, server/getSettings.js, server/render-middleware.js, src/components/BaseCommentForm.js, src/components/SortableCommentList.js, src/config.js, src/utils/section.js, yarn.lock
Add capability to disable comments on maintenance mode if needed
Pipeline changes:
- https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/5772
=> KER-235 Disable comments on maintenance mode

cities/helsinki/i18n/service-info/content.en.md, cities/helsinki/i18n/service-info/content.fi.md, cities/helsinki/i18n/service-info/content.sv.md
Content updated based attachment provided in https://helsinkisolutionoffice.atlassian.net/browse/KER-217
=> Update service information content

__tests__/UserProfile/UserComment.react-test.jsx, __tests__/UserProfile/UserProfile.react-test.jsx, package.json, src/components/BaseCommentForm.jsx, src/components/Hearing/Comment/index.jsx, src/components/Hearing/Header.jsx, src/components/Hearing/Section/SectionContainer.jsx, src/components/OverviewMap.jsx, src/components/PluginContent.jsx, src/components/UserComment/UserComment.jsx, src/components/admin/ContactModal.jsx, src/components/admin/HearingFormStep3.jsx, src/components/admin/HearingFormStep5.jsx, src/components/plugins/MapQuestionnaire.jsx, src/getRoot.jsx, src/views/UserProfile/index.jsx
Removed a component from react-bootstrap during update before reverting the change and forgot to reintroduce the import.
=> Fix: Added removed import

azure-pipelines-build-pr.yml
Co-PR: https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/6118
=> Add pipeline for PR testing

src/components/BaseCommentForm.jsx, src/components/plugins/MapQuestionnaire.jsx
Fixing hearing map comment bug
https://helsinkisolutionoffice.atlassian.net/browse/KER-268
=> KER-268 fix hearing map comment bug

package.json
=> release-1.1.0 bump version number

src/components/Hearing/Comment/index.jsx
Kerrokantasi-peukuttaminen ei onnistu
jossain vaiheessa tiedostoa on refaktoroitu niin että onVote function this konteksti on hukattu.
=> KER-271: Kerrokantasi-peukuttaminen ei onnistu

src/middleware/language.js
[PR983](https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/983) fixed language change from query params, but it broke language change from UI. So this PR fix also that.
=> KER-277 fix language change from ui

src/components/admin/HearingFormStep1.jsx
Fixing bug: not able to create new contacts.
Closes: [KER-275](https://helsinkisolutionoffice.atlassian.net/browse/KER-275)
[KER-275]: https://helsinkisolutionoffice.atlassian.net/browse/KER-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KER-275 Bug: create contact not working

assets/sass/kerrokantasi/_hearing-page.scss, conf/webpack/common.js, src/components/BaseCommentForm.jsx, src/components/Hearing/Section/SubSectionsList.jsx
Bug fixes:
- [fix: map button svgs not visible KER-99](https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/994/commits/d40020667b037aa2f90bd1cd6d99bc8919e3a021)
- [fix: base comment form add images KER-99](https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/994/commits/e474d06b7d0b0c1a38310995ebe8f1728f3e6670)
- [fix: base comment form add comment button width KER-99](https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/994/commits/5efd4343da5b05ea684b3f6a4173c4c200894da1)
=> KER-99 bug fixes

pipelines/kerrokantasi-ui-dev.yml, pipelines/kerrokantasi-ui-release.yml, pipelines/kerrokantasi-ui-review.yml
[OH-45](https://helsinkisolutionoffice.atlassian.net/browse/OH-45)
-----------------------------------------------------------------------------------------------
1. Tiedosto 
* Selitys muutoksista
2. Tiedosto
* Selitys muutoksista
3. Tiedosto
* Selitys muutoksista
1. Tiedosto 
* Selitys muutoksista
2. Tiedosto
* Selitys muutoksista
3. Tiedosto
* Selitys muutoksista
[OH-45]: https://helsinkisolutionoffice.atlassian.net/browse/OH-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: pipeline trigger exclude .md from root only OH-45

package.json
Updated versioning at package json to indicate new release.
=> fix: updated versioning

src/components/Header/Header.jsx, src/components/Hearing/Header.jsx, src/components/OverviewMap.jsx, src/components/admin/HearingFormStep1.jsx, src/components/admin/HearingFormStep2.jsx, src/components/admin/SectionForm.jsx
Fix to uploading attachments to hearing.
Component was not receiving the language from this.context, reason most likely being react version upgrades earlier.
Changed to use language from store.
Implemented change to all other places using this.context as it most likely was silently broken in those places aswell.
=> KER-330 attachment fix

src/actions/user.js, src/reducers/hearingEditor/hearing.js
I suspect this react state console error is the main culpirit for causing the blank page appearing, I'm not entirely sure why it would sometimes work and sometimes not.
=> fix: fixing label console errors, expected to be cause for blank page

src/utils/oidcConfig.js
=> fix: remove profiili config temporarily

src/utils/oidcConfig.js
Title says it all
fix: guess who's back, back again, profiili is back
=> KER-333 refix

assets/urls.json, cities/helsinki/assets/urls.json, src/components/Footer.jsx, src/utils/__tests__/languageUtils.test.js, src/utils/languageUtils.js, src/views/NewHearing/NewHearingContainer.jsx, src/views/__tests__/__snapshots__/Home.test.jsx.snap
Footer links were broken on non-finnish languages.
Footer links have been updated to support non-finnish languages.
=> fix: fixed broken footer links for all non-finnish languages

src/components/Hearing/Section/SectionContainer.jsx, src/components/Hearing/Section/SubSectionsList.jsx
Subsections list should always show Comment button, even if subsection requires authentication.
=> fix: subsections should show comment if not authenticated KER-361

cities/helsinki/i18n/service-info/content.en.md, cities/helsinki/i18n/service-info/content.fi.md, cities/helsinki/i18n/service-info/content.sv.md
Text changes for Service Info page to accomodate new Helsinki Tunnus.
=> feat: new service-info texts for profile change

assets/sass/kerrokantasi/_common.scss, assets/sass/kerrokantasi/_hearing-form.scss, cities/helsinki/assets/sass/hel/_hearing-form.scss, cities/helsinki/assets/sass/hel/variables.scss, src/components/BaseCommentForm.jsx, src/components/CommentReportModal/CommentReportModal.jsx, src/components/DeleteModal.jsx, src/components/RichTextEditor/Iframe/IframeModal.jsx, src/components/RichTextEditor/Image/ImageModal.jsx, src/components/RichTextEditor/SkipLink/SkipLinkModal.jsx, src/components/admin/ContactModal.jsx, src/components/admin/HearingForm.jsx, src/components/admin/LabelModal.jsx, src/components/admin/__tests__/ContactModal.test.jsx
Fix Dialog theme and buttons to match KK theme.
=> fix: dialogs use correct colors KER-298

src/components/Hearing/Comment/index.jsx, src/components/admin/HearingForm.jsx, src/components/admin/HearingToolbar.jsx
- Add missing KK button class
- Hearing form fix dialog buttons order
=> KER-298 button fixes

src/createStore.js, src/index.js, src/utils/sentry/__tests__/sentry.test.js, src/utils/sentry/index.js
Clear sensitive data from sentry logs.
=> Sentry clear sensitive data KER-376

e2e/tests/pages/hearing.spec.js
=> chore: fixing hearing e2e tests

src/components/Hearing/Section/SectionAttachment.jsx, src/components/Hearing/Section/__tests__/SectionAttachment.test.jsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Return default attachment title if not available.
=> fix: section attachment default title KER-378

src/reducers/hearingEditor/__tests__/labels.test.js, src/reducers/hearingEditor/__tests__/organizations.test.js, src/reducers/hearingEditor/labels.js, src/reducers/hearingEditor/organizations.js, src/selectors/hearingEditor/__tests__/index.test.js, src/selectors/hearingEditor/index.js
Trying to fix normalize hearing data bug.
=> fix: normalize hearing data bug KER-378

src/actions/hearingEditor.js
Reverting hearingEditor action changes.
=> fix: revert hearingEditor action changes KER-378

src/views/Hearing/HearingContainer.jsx
Trying to reduce amount of actions triggered on hearing page.
=> fix: hearing page limit amount of actions KER-378

src/views/Hearing/HearingContainer.jsx
Reduce hearing actions when logged in.
=> fix: reduce hearing actions when logged in KER-378

src/components/Hearing/Section/SectionContainer.jsx, src/components/Hearing/Section/__tests__/SectionContainer.test.jsx
- SectionContainer state fixes
- SectionContainer to function component
=> SectionContainer state fixes KER-378

src/utils/sentry/index.js
Sentry should only handle clone of the actual data.
=> Sentry clean sensitive data clone KER-378

.github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/release-please.yml, README.md, deploy/containerize.sh, pipelines/kerrokantasi-ui-dev.yml, pipelines/kerrokantasi-ui-review.yml
This PR includes changes required after changing the `master` branch to `main`.
=> KER-379 | Rename master branch to main

src/components/QuestionForm/__tests__/QuestionForm.test.jsx, src/components/QuestionForm/index.jsx
QuestionForm remove bootstrap.
=> KER-346 QuestionForm remove bootstrap

src/components/UserHearings/HearingFormControl.jsx, src/components/UserHearings/__tests__/HearingFormControl.test.jsx, src/views/UserHearings/index.jsx
HearingFormControl remove bootstrap.
=> KER-346 HearingFormControl remove bootstrap

assets/sass/kerrokantasi/_hearing-page.scss, src/components/BaseCommentForm.jsx, src/components/__tests__/BaseCommentForm.jsx, src/components/plugins/legacy/mapdon-hkr.jsx, src/components/plugins/legacy/mapdon-ksv.jsx
BaseCommentForm remove bootstrap
=> KER-346 BaseCommentForm remove bootstrap

src/components/CommentReportModal/CommentReportForm.jsx
=> fix: comment report form, broken error toast KER-346

assets/sass/kerrokantasi/_commentlist.scss, src/components/Hearing/CommentList/index.jsx, src/components/SortableCommentList.jsx, src/components/__tests__/SortableCommentList.test.jsx, src/components/plugins/MapQuestionnaire.jsx, src/components/plugins/legacy/mapdon-hkr.jsx, src/components/plugins/legacy/mapdon-ksv.jsx
- Map questionnaire (and legacy plugins)  remove bootstrap KER-346.
- SortableCommentList remove bootstrap KER-346
- SortableCommentList to function KER-346
=> KER-346 Map questionnaire remove bootstrap

src/views/Auth/logoutCallback.jsx
Fixed login callback using old Tunnistamo oidc signout method.
=> fix: fixed login callback using old setup

cities/helsinki/i18n/accessibility-info/accessibility.en.md, cities/helsinki/i18n/accessibility-info/accessibility.fi.md, cities/helsinki/i18n/accessibility-info/accessibility.sv.md, src/views/AccessibilityInfo/index.jsx, src/views/__tests__/__snapshots__/Home.test.jsx.snap
Saavutettavuusselosteen yhteystietojen (Traficom) päivitys
https://helsinkisolutionoffice.atlassian.net/browse/RATY-160
=> chore: update traficom contact info RATY-160

src/App.jsx, src/actions/index.js, src/components/BaseCommentForm.jsx, src/components/DeleteModal.jsx, src/components/Header/Header.jsx, src/components/Header/__tests__/Header.test.jsx, src/components/Hearing/Comment/index.jsx, src/components/Hearing/Section/SectionContainer.jsx, src/components/Hearing/Section/__tests__/SectionContainer.test.jsx, src/components/SortableCommentList.jsx, src/components/__tests__/BaseCommentForm.jsx, src/components/plugins/MapQuestionnaire.jsx, src/components/plugins/legacy/mapdon-hkr.jsx, src/components/plugins/legacy/mapdon-ksv.jsx, src/utils/section.js, src/views/FullscreenHearing/FullscreenHearingContainer.jsx, src/views/Hearing/__tests__/HearingContainer.test.jsx, test-utils.js
- Fixing voting on comment checkboxes: https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/1109/commits/9d567f4667b3122f074b8385ee3d8151076684c7
- Always include given organisation in comment request if available: https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/1109/commits/3df3e368e63e0a342e0990665cd011cedd49a853, https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/1109/commits/30c3772902761460e1bec2fc79bc5337fc783582
- Fix being able to close comment editor from inside the component: https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/1109/commits/b981510c8c08b75446baf2a61c42a6b51467918d
- Deleting comments fixed: https://github.com/City-of-Helsinki/kerrokantasi-ui/pull/1109/commits/1672fd32835b206304d4e086fdad0df877342148
- Fixing changing languages causing the …
=> KER-422 Comment bugs

src/components/BaseCommentForm.jsx, src/components/Hearing/Section/SectionContainer.jsx, src/components/RichTextEditor/Image/ImageModal.jsx, src/components/admin/HearingEditor.jsx, src/components/admin/HearingFormStep3.jsx, src/components/admin/SectionForm.jsx, src/utils/constants.jsx
Prohibits uploading random files to comment, now only accepts images.
=> fix: added filetype restriction to commentform

src/actions/hearingEditor.js, src/components/admin/HearingEditor.jsx
Should run prepareHearingForSave on every occasion.
=> fix: hearingEditor attachments KER-449

src/middleware/hearingEditor.js
Normalize saved hearing isNew should be set to false.
=> fix: normalizeSavedHearing isNew KER-449

.env, .env.local.example, assets/urls.json, cities/helsinki/assets/urls.json, src/components/BaseCommentForm.jsx, src/components/OverviewMap.jsx, src/components/admin/HearingFormStep3.jsx, src/config.js
refs: RATYK-54
Co-PR: https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/11482
=> feat: add configurable tile server urls

package.json, yarn.lock
Bump @babel/helpers to 7.27.0.
=> deps: @babel/helpers to 7.27.0 KER-404

package.json, yarn.lock
Set micromatch resolution to 4.0.8.
=> deps: bump micromatch to 4.0.8 KER-404

e2e/tests/login.spec.js
https://helsinkisolutionoffice.atlassian.net/browse/KEH-108
=> fix: login test skip if missing credentials

assets/sass/kerrokantasi/_common.scss
Minor fix for the stylings of the notification component.
=> fix: fixed empty margins when no notifications are shown

src/components/Hearing/Section/SectionContainer.jsx, src/components/Hearing/Section/__tests__/SectionContainer.test.jsx, src/i18n/en.json, src/i18n/fi.json, src/i18n/sv.json
Fixing download hearing comment summary link.
https://helsinkisolutionoffice.atlassian.net/browse/KER-494
=> fix: download hearing comment summary KER-494

assets/sass/kerrokantasi/_common.scss, src/components/CommentDisclaimer.jsx, src/components/Footer.jsx, src/components/Hearing/Comment/index.jsx, src/components/Hearing/Section/SectionAttachment.jsx, src/components/MarkdownLinkRenderer/MarkdownLinkRenderer.jsx, src/components/MarkdownPage/MarkdownPage.jsx, src/components/RichTextEditor/index.jsx, src/components/UserComment/UserComment.jsx, src/components/admin/HearingForm.jsx, src/views/AccessibilityInfo/index.jsx, src/views/BrowserWarning/index.jsx, src/views/Info/index.jsx
Prevent any links opening in new tab or window. 
https://helsinkisolutionoffice.atlassian.net/browse/KER-529
=> feat: prevent links opening in new tab Ref: KER-529

.github/workflows/ci.yaml, package.json, sonar-project.properties
Common CI workflow
https://helsinkisolutionoffice.atlassian.net/browse/KER-461
Related azure pipeline PR:
https://dev.azure.com/City-of-Helsinki/kerrokantasi/_git/kerrokantasi-pipelines/pullrequest/11922
=> ci: common CI workflow KER-461
